apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvs-image-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvs-image-products
  template:
    metadata:
      labels:
        app: tvs-image-products
    spec:
      containers:
        - name: tvs-image-products
          image: gcr.io/niveus-research-project/tvs-image-products:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: service-key
            mountPath: "/app/credentials/project-development"
            readOnly: true
        volumes:
        - name: service-key
          secret:
            secretName: project-development   
